import { CarRental, GamepadOutlined, Games, GamesOutlined, GamesTwoTone, Masks, Movie, MovieCreationSharp, MovieFilter, MusicNoteOutlined, People, Pets, Sports, SportsBasketball, TravelExplore, VideoCameraBack } from "@mui/icons-material";

const youtubeCategories = [
    { id: '1', title: 'Film & Animation', icon: <Movie/> },
    { id: '2', title: 'Autos & Vehicles', icon: <CarRental/> },
    { id: '10', title: 'Music', icon: <MusicNoteOutlined/> },
    { id: '15', title: 'Pets & Animals', icon: <Pets/> },
    { id: '17', title: 'Sports', icon: <SportsBasketball/> },
    { id: '18', title: 'Short Movies', icon: <MovieFilter/> },
    { id: '19', title: 'Travel & Events', icon: <TravelExplore/> },
    { id: '20', title: 'Gaming', icon: <GamesTwoTone/> },
    { id: '21', title: 'Videoblogging', icon: <VideoCameraBack/> },
    { id: '22', title: 'People & Blogs', icon: <People/>},
    { id: '23', title: 'Comedy' },
    { id: '24', title: 'Entertainment' },
    { id: '25', title: 'News & Politics' },
    { id: '26', title: 'Howto & Style' },
    { id: '27', title: 'Education' },
    { id: '28', title: 'Science & Technology' },
    { id: '29', title: 'Nonprofits & Activism' },
    { id: '30', title: 'Movies' },
    { id: '31', title: 'Anime/Animation' },
    { id: '32', title: 'Action/Adventure' },
    { id: '33', title: 'Classics' },
    { id: '34', title: 'Comedy' },
    { id: '35', title: 'Documentary' },
    { id: '36', title: 'Drama' },
    { id: '37', title: 'Family' },
    { id: '38', title: 'Foreign' },
    { id: '39', title: 'Horror' },
    { id: '40', title: 'Sci-Fi/Fantasy' },
    { id: '41', title: 'Thriller' },
    { id: '42', title: 'Shorts' },
    { id: '43', title: 'Shows' },
    { id: '44', title: 'Trailers' },
  ];

export default youtubeCategories